#include <string.h>

#define NOB_IMPLEMENTATION
#define NOB_STRIP_PREFIX
#include "nob.h"

Cmd cmd = {0};

#define OUTPUT_DIR "bin/"
#define RELEASE_DIR "dist/"
#define ASSETS_INPUT_DIR "assets/"
#define ASSETS_OUTPUT_DIR "src/"
#define INPUT_FILES "src/main.c"

//// Asset packer/generator ////

typedef enum {
	ASSET_PNG,
	ASSET_TTF,
	ASSET_OTHER,
} AssetKind;

typedef struct {
	const char* path;
	const char* name;
	AssetKind kind;
} Asset;

typedef struct {
	Asset* items;
	size_t count, capacity;
} Assets;

bool collect_assets(const char* asset_dir, Assets* target) {
	File_Paths dir = {0};
	if (!nob_read_entire_dir(asset_dir, &dir)) return false;
	da_foreach(const char*, path, &dir) {
		const char* real_path = temp_sprintf("%s/%s", asset_dir, *path);
		if (get_file_type(real_path) != NOB_FILE_REGULAR) continue;
		String_View sv = sv_from_cstr(*path);
		AssetKind k = ASSET_OTHER;
		
		if      (sv_end_with(sv, ".png")) k = ASSET_PNG;
		else if (sv_end_with(sv, ".ttf")) k = ASSET_TTF;
		String_View name = sv_chop_by_delim(&sv, '.');
		
		da_append(target, ((Asset){
			.path = strdup(real_path), // leaking some memory but it's ok
			.name = strdup(temp_sv_to_cstr(name)),
			.kind = k,
		}));
	}
	return true;
}

bool pack_assets(Assets assets, const char* output_assets_dir) {
	String_Builder output = {0};
	String_Builder file_content = {0};
	sb_appendf(&output, "// Generated by Inkpad's asset packer\n");
	sb_appendf(&output, "// DO NOT MODIFY THIS FILE. AUTOMATICALLY GENERATED\n");
	sb_appendf(&output, "// (c) 2026 Marcio Dantas\n");
	da_foreach(Asset, asset, &assets) {
		file_content.count = 0;
		switch (asset->kind) {
		case ASSET_PNG: {
			if (!nob_read_entire_file(asset->path, &file_content)) return false;
			sb_appendf(&output, "unsigned char %s_png[] = { ", asset->name);
			da_foreach(char, byt, &file_content) sb_appendf(&output, "%d, ", *byt);
			sb_appendf(&output, "};\n");
		} break;
		case ASSET_TTF: {
			if (!nob_read_entire_file(asset->path, &file_content)) return false;
			sb_appendf(&output, "unsigned char %s_ttf[] = { ", asset->name);
			da_foreach(char, byt, &file_content) sb_appendf(&output, "%d, ", *byt);
			sb_appendf(&output, "};\n");
		} break;
		case ASSET_OTHER:
		default:
			nob_log(NOB_ERROR, "Unsupported asset `%s`", asset->path);
			return false;
		}
		sb_appendf(&output, "unsigned long long %s_size = %lu;\n", asset->name, file_content.count);
	}
	write_entire_file(
		temp_sprintf("%s/assets.c", output_assets_dir),
		output.items,
		output.count
	);
	return true;
}

//// Build system ////

bool release(const char* name, const char* build_path) {
	char* name_dir = strdup(temp_sprintf(RELEASE_DIR"%s", name));
	if (!mkdir_if_not_exists(RELEASE_DIR)) return false;
	if (!mkdir_if_not_exists(name_dir)) return false;
	if (!copy_directory_recursively(build_path, name_dir)) return false;

	cmd_append(&cmd, "zip", "-r", temp_sprintf("%s.zip", name), name_dir);

	return cmd_run(&cmd);
}

bool build_linux_x86_64(bool debug) {
	const char* output = OUTPUT_DIR"linux-x86_64/inkpad";
	if (!mkdir_if_not_exists(OUTPUT_DIR"linux-x86_64")) return false;

	// basic compilation
	cmd_append(&cmd, "gcc", "-o", output, INPUT_FILES);
	
	// compiler flags
	cmd_append(&cmd, "-Wall", "-Wextra");

	// Debug
	if (debug) cmd_append(&cmd, "-DDEBUG");
	
	// linking and include
	cmd_append(&cmd, "-I/usr/local/include", "-lraylib", "-lm");

	return cmd_run(&cmd);
}

bool build_windows_x86_64(bool debug) {
	const char* output = OUTPUT_DIR"windows-x86_64/inkpad";
	if (!mkdir_if_not_exists(OUTPUT_DIR"windows-x86_64")) return false;
	
	// basic compilation
	
	cmd_append(&cmd, "x86_64-w64-mingw32-gcc-win32", "-o", OUTPUT_DIR"windows-x86_64/inkpad.exe", INPUT_FILES);
	
	// compiler flags
	cmd_append(&cmd, "-Wall", "-Wextra");

	// debug
	if (debug) cmd_append(&cmd, "-DDEBUG");

	// linking and include
	cmd_append(&cmd, "-I/usr/local/include", "-L./lib", "-lraylib", "-lwinmm", "-lgdi32");

	if (!cmd_run(&cmd)) return false;
	
	return true;
}

typedef struct {
	const char* name;
	bool (*build)(bool);
} Platform;

static const Platform platforms[] = {
	{ // 0th item is the default platform to build
		.name = "linux-x86_64",
		.build = &build_linux_x86_64,
	},
	{
		.name = "windows-x86_64",
		.build = &build_windows_x86_64,
	},
};

bool delete_dir(const char* path) {
	File_Paths dir = {0};
	if (!nob_read_entire_dir(path, &dir)) return false;
	da_foreach(const char*, p, &dir) {
		if (strcmp(*p, ".") == 0 || strcmp(*p, "..") == 0) continue;

		const char* real_path = temp_sprintf("%s/%s", path, *p);
		File_Type ty = get_file_type(real_path);
		
		if (ty == NOB_FILE_REGULAR) {
			if (!delete_file(real_path)) return false;
		} else if (ty == NOB_FILE_DIRECTORY) {
			if (!delete_dir(real_path)) return false;
		}
	}
	if (!delete_file(path)) return false;
	return true;
}

// NOTE: Do not forget to delete files/folders here
//       if you create them in other parts of the build system 
bool clean(void) {
	File_Paths dir = {0};
	if (!nob_read_entire_dir(get_current_dir_temp(), &dir)) return false;
	da_foreach(const char*, path, &dir) {
		String_View sv = sv_from_cstr(*path);
		if (sv_end_with(sv, ".zip")) {
			if (!delete_file(sv.data)) return false;
		}
	}
	
	if (!delete_dir(OUTPUT_DIR)) return false;
	if (!delete_dir(RELEASE_DIR)) return false;

	return true;
}

int main(int argc, char** argv) {
	NOB_GO_REBUILD_URSELF(argc, argv);

	if (!mkdir_if_not_exists(OUTPUT_DIR)) return 1;

	assert(ARRAY_LEN(platforms) >= 1);
	if (argc <= 1) {
		Platform plat = platforms[0];
		nob_log(NOB_WARNING, "Platform not provided. Defaulting to %s", plat.name);
		nob_log(NOB_INFO, "Building Inkpad for %s", plat.name);
		if (!(*plat.build)(true)) return 1;
		return 0;
	}

	if (strcmp(argv[1], "release") == 0) {
		for (size_t i = 0; i < ARRAY_LEN(platforms); i++) {
			Platform plat = platforms[i];
			nob_log(NOB_INFO, "Releasing Inkpad for %s", plat.name);
			if (argc < 3) {
				if (!(*plat.build)(false)) return 1;
				release(temp_sprintf("inkpad-%s", plat.name), temp_sprintf(OUTPUT_DIR"%s", plat.name));
			} else if (strcmp(argv[1], plat.name) == 0) {
				if (!(*plat.build)(false)) return 1;
				release(temp_sprintf("inkpad-%s", plat.name), temp_sprintf(OUTPUT_DIR"%s", plat.name));
				return 0;
			}
		}
		return 0;
	}

	if (strcmp(argv[1], "clean") == 0) {
		if (!clean()) return 1;
		return 0;
	}

	if (strcmp(argv[1], "run") == 0) {
		Platform plat = platforms[0];
		nob_log(NOB_INFO, "Building + Running Inkpad for %s", plat.name);
		if (!(*plat.build)(true)) return 1;
		cmd_append(&cmd, temp_sprintf("./%s/%s/inkpad", OUTPUT_DIR, plat.name));
		if (!cmd_run(&cmd)) return 1;
		return 0;
	}
	
	if (strcmp(argv[1], "pack") == 0) {
		if (!mkdir_if_not_exists(ASSETS_OUTPUT_DIR)) return 1;
		nob_log(NOB_INFO, "Packing assets in `%s` into `%s`", ASSETS_INPUT_DIR, ASSETS_OUTPUT_DIR);
		Assets assets = {0};
		if (!collect_assets(ASSETS_INPUT_DIR, &assets)) return 1;
		if (!pack_assets(assets, ASSETS_OUTPUT_DIR)) return 1;
		return 0;
	}
	
	if (strcmp(argv[1], "help") == 0) {
		nob_log(NOB_INFO, "Usage: nob COMMAND");
		nob_log(NOB_INFO, "Available commands:");
		printf("    PLATFORM: Build for a platform (see available platforms below)\n");
		printf("    `release [PLATFORM]`: Release for a platform (or all if not provided)\n");
		printf("    `pack`: Pack the application's assets\n");
		printf("    `run`: Build and run for the default platform (development purposes)\n");
		printf("    `clean`: Clean up build garbage\n");
		printf("    `help`: Show this help message\n");
		nob_log(NOB_INFO, "Available platforms:");
		for (size_t i = 0; i < ARRAY_LEN(platforms); i++) {
			printf("    `%s`: Build Inkpad for %s\n", platforms[i].name, platforms[i].name);
		}
		return 0;
	}

	nob_log(NOB_ERROR, "Invalid platform or command `%s`", argv[1]);
	nob_log(NOB_INFO, "Use `help` to see help message");

	return 0;
}
