static const char* fxaa_shader =
	"#version 330\n"
	"#define FXAA_REDUCE_MIN (1.0/128.0)\n"
	"#define FXAA_REDUCE_MUL (1.0/8.0)\n"
	"#define FXAA_SPAN_MAX 8.0\n"
	"in vec2 fragTexCoord;\n"
	"in vec4 fragColor;\n"
	"out vec4 finalColor;\n"
	"uniform sampler2D texture0;\n"
	"uniform vec2 resolution;\n"
	"void main() {\n"
	"vec2 inverse_resolution = vec2(1.0/resolution.x, 1.0/resolution.y);\n"
	"vec3 rgbNW = texture2D(texture0, fragTexCoord.xy + (vec2(-1.0,-1.0)) * inverse_resolution).xyz;\n"
	"vec3 rgbNE = texture2D(texture0, fragTexCoord.xy + (vec2(1.0,-1.0)) * inverse_resolution).xyz;\n"
	"vec3 rgbSW = texture2D(texture0, fragTexCoord.xy + (vec2(-1.0,1.0)) * inverse_resolution).xyz;\n"
	"vec3 rgbSE = texture2D(texture0, fragTexCoord.xy + (vec2(1.0,1.0)) * inverse_resolution).xyz;\n"
	"vec3 rgbM  = texture2D(texture0, fragTexCoord.xy).xyz;\n"
	"vec3 luma = vec3(0.299, 0.587, 0.114);\n"
	"float lumaNW = dot(rgbNW, luma);\n"
	"float lumaNE = dot(rgbNE, luma);\n"
	"float lumaSW = dot(rgbSW, luma);\n"
	"float lumaSE = dot(rgbSE, luma);\n"
	"float lumaM  = dot(rgbM,  luma);\n"
	"float lumaMin = min(lumaM, min(min(lumaNW, lumaNE), min(lumaSW, lumaSE)));\n"
	"float lumaMax = max(lumaM, max(max(lumaNW, lumaNE), max(lumaSW, lumaSE))); \n"
	"vec2 dir;\n"
	"dir.x = -((lumaNW + lumaNE) - (lumaSW + lumaSE));\n"
	"dir.y =  ((lumaNW + lumaSW) - (lumaNE + lumaSE));\n"
	"float dirReduce = max((lumaNW + lumaNE + lumaSW + lumaSE) * (0.25 * FXAA_REDUCE_MUL), FXAA_REDUCE_MIN);\n"
	"float rcpDirMin = 1.0 / (min(abs(dir.x), abs(dir.y)) + dirReduce);\n"
	"dir = min(vec2(FXAA_SPAN_MAX, FXAA_SPAN_MAX),\n"
	"    max(vec2(-FXAA_SPAN_MAX, -FXAA_SPAN_MAX), dir * rcpDirMin))\n"
	"* inverse_resolution;\n"
	"vec3 rgbA = 0.5 * (\n"
	"texture2D(texture0, fragTexCoord.xy + dir * (1.0/3.0 - 0.5)).xyz +\n"
	"texture2D(texture0, fragTexCoord.xy + dir * (2.0/3.0 - 0.5)).xyz\n"
	");\n"
	"vec3 rgbB = rgbA * 0.5 + 0.25 * (\n"
	"texture2D(texture0, fragTexCoord.xy + dir * -0.5).xyz +\n"
	"texture2D(texture0, fragTexCoord.xy + dir * 0.5).xyz\n"
	");\n"
	"float lumaB = dot(rgbB, luma);\n"
	"if ((lumaB < lumaMin) || (lumaB > lumaMax)) finalColor = vec4(rgbA, 1.0);\n"
	"else finalColor = vec4(rgbB, 1.0);\n"
	"}\n";
